# Generated by Django 3.2.4 on 2021-06-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0002_alter_pizza_toppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='sizes',
            field=models.ManyToManyField(related_name='pizzas', to='pizzaapp.Size'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='types',
            field=models.ManyToManyField(related_name='pizzas', to='pizzaapp.Type'),
        ),
    ]
