# Generated by Django 3.2.4 on 2021-06-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0003_auto_20210619_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Square', 'Square')], max_length=50, null=True),
        ),
    ]
