# Generated by Django 3.2.4 on 2021-06-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0004_alter_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Square', 'Square')], default='Regular', max_length=50),
        ),
    ]
