# Generated by Django 3.2.4 on 2021-06-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0005_alter_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(default='pizzaname', max_length=50),
        ),
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.CharField(default='toppingname', max_length=50),
        ),
    ]
