# Generated by Django 3.2.4 on 2021-06-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0007_auto_20210620_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='val',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Extra-Large', 'Extra-Large')], default='Small', max_length=50),
        ),
    ]
